gestion_scolaire/cours/urls.py
from django.urls import path

from .views import (
    create_module,
    module_list_view,
    create_matiere,
    matiere_list_view,
    cours_dashboard_view,
    matiere_detail_view,
    matiere_view,
)


app_name = "cours"
urlpatterns = [
    path("modules/ajouter", module_list_view, name="ajouter_module"),
    path("modules", module_list_view, name="modules"),
    path("matieres/ajouter", matiere_list_view, name="ajouter_matiere"),
    path("matieres", matiere_list_view, name="matieres"),
    path("tableau-de-bord", cours_dashboard_view, name="dashboard"),
    path("mesma", matiere_view, name="mat"),
    path("matieres/<int:pk>/", matiere_detail_view, name="matiere"),
]

gestion_scolaire/etudiants/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (
    etudiant_list_view,
    etudiant_detail_view,
    etudiant_inscription_view,
    etudiant_update_view,
    etudiant_matiere_view,
    etudiant_note_view,
)

app_name = "etudiants"
urlpatterns = [
    path("ajouter", etudiant_list_view, name="ajouter"),
    path("", etudiant_list_view, name="etudiants"),
    path("matieres/", etudiant_matiere_view, name="matieres"),
    path("notes/", etudiant_note_view, name="notes"),
    path("<int:pk>/", etudiant_detail_view, name="etudiant"),
    path("<int:pk>/inscription/", etudiant_inscription_view, name="inscription"),
    path("<int:pk>/modifier/", etudiant_update_view, name="editer"),
]

gestion_scolaire/gestion_scolaire/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("comptes.urls")),
    path("staffs/", include("staffs.urls")),
    path("parcours/", include("parcours.urls")),
    path("cours/", include("cours.urls")),
    path("enseignants/", include("enseignants.urls")),
    path("etudiants/", include("etudiants.urls")),
    path("evaluations/", include("notes.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion_scolaire/etudiants/models.py
from django.db import models

from comptes.models import Compte, Information
from parcours.models import Specialite
from cours.models import GRADES


GROUPE_SANGUIN = (
    ("A+", "A+"),
    ("A-", "A-"),
    ("AB+", "AB+"),
    ("AB-", "AB-"),
    ("B+", "B+"),
    ("B-", "B-"),
    ("O+", "O+"),
    ("O-", "O-"),
)


class Etudiant(Information):
    compte = models.OneToOneField(
        Compte, primary_key=True, on_delete=models.CASCADE, related_name="etudiant"
    )
    groupe_sanguin = models.CharField(choices=GROUPE_SANGUIN, max_length=20)


class Inscription(models.Model):
    etudiant = models.ForeignKey(Etudiant, on_delete=models.CASCADE, related_name="inscriptions")
    specialite = models.ForeignKey(Specialite, on_delete=models.CASCADE)
    grade = models.CharField(max_length=20, choices=GRADES)
    annee = models.CharField(max_length=20)

gestion_scolaire/etudiants/forms.py
from django import forms

from pays import Countries
from datetime import date

from parcours.models import Specialite
from cours.models import GRADES
from comptes.models import SEXES

from .models import Etudiant, GROUPE_SANGUIN


PAYS = list()
for country in Countries():
    PAYS.append((country.name, country.name))

year = date.today().year - 3

ANNEES = (
    ((f'{year}{" - "}{year + 1}'), (f'{year}{" - "}{year + 1}')),
    ((f'{year + 1}{" - "}{year + 2}'), (f'{year + 1}{" - "}{year + 2}')),
    ((f'{year + 2}{" - "}{year + 3}'), (f'{year + 2}{" - "}{year + 3}')),
    ((f'{year + 3}{" - "}{year + 4}'), (f'{year + 3}{" - "}{year + 4}')),
    ((f'{year + 4}{" - "}{year + 5}'), (f'{year + 4}{" - "}{year + 5}')),
    ((f'{year + 5}{" - "}{year + 6}'), (f'{year + 5}{" - "}{year + 6}')),
)


class EtudiantCreationForm(forms.Form):
    nom = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Nom",
            }
        ),
        max_length=255,
    )
    prenom = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Prénom",
            }
        ),
        max_length=255,
    )
    date_de_naissance = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "datepicker_input form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "JJ/MM/AAAA",
            }
        ),
        max_length=255,
    )
    sexe = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Sexe",
            }
        ),
        choices=SEXES,
    )
    pays = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Sexe",
            }
        ),
        choices=PAYS,
    )
    groupe_sanguin = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Sexe",
            }
        ),
        choices=GROUPE_SANGUIN,
    )
    photo = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                "class": "form-control form-control-lg shadow-none",
                "id": "formFileLg",
                "placeholder": "Email",
            }
        ),
        max_length=255,
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Email",
            }
        ),
        max_length=255,
    )
    telephone = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Téléphone",
            }
        ),
        max_length=255,
    )


class EtudiantUpdateForm(forms.Form):
    nom = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Nom",
            }
        ),
        max_length=255,
    )
    prenom = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Prénom",
            }
        ),
        max_length=255,
    )
    date_de_naissance = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "datepicker_input form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "JJ/MM/AAAA",
            }
        ),
        max_length=255,
    )
    sexe = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Sexe",
            }
        ),
        choices=SEXES,
    )
    pays = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Sexe",
            }
        ),
        choices=PAYS,
    )
    groupe_sanguin = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Sexe",
            }
        ),
        choices=GROUPE_SANGUIN,
    )
    photo = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                "class": "form-control form-control-lg shadow-none",
                "id": "formFileLg",
                "placeholder": "Email",
            }
        ),
        max_length=255,
    )
    telephone = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Téléphone",
            }
        ),
        max_length=255,
    )


class InscriptionForm(forms.Form):
    specialite = forms.ModelChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Spécialité",
            }
        ),
        queryset=Specialite.objects.all(),
        empty_label="----------------------------",
    )
    grade = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Grade",
            }
        ),
        choices=GRADES,
    )
    annee = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Année Académique",
            }
        ),
        choices=ANNEES,
    )

gestion_scolaire/etudiants/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db import transaction
from django.contrib.auth.decorators import login_required, user_passes_test

from datetime import datetime

from comptes.models import Compte, get_country_code
from staffs.views import is_staff, is_not_anonymous, is_etudiant
from parcours.models import Specialite
from cours.models import Module, Matiere
from notes.models import Note

from .models import Etudiant, Inscription
from .forms import EtudiantCreationForm, InscriptionForm, EtudiantUpdateForm


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_staff, login_url="/")
@login_required(login_url="/")
def etudiant_list_view(request):
    etudiants = Etudiant.objects.all()

    if request.method == "POST":
        compte = Compte()
        etudiant = Etudiant()

        form = EtudiantCreationForm(request.POST, request.FILES)

        if form.is_valid():
            compte.telephone = form.cleaned_data["telephone"]
            compte.email = form.cleaned_data["email"]
            compte.photo = request.FILES["photo"]
            compte.type_de_compte = "ET"
            compte.save()

            etudiant.compte = compte
            etudiant.nom = form.cleaned_data["nom"]
            etudiant.prenom = form.cleaned_data["prenom"]
            etudiant.sexe = form.cleaned_data["sexe"]
            etudiant.date_de_naissance = form.cleaned_data["date_de_naissance"]
            etudiant.pays = form.cleaned_data["pays"]
            etudiant.groupe_sanguin = form.cleaned_data["groupe_sanguin"]

            etudiant.matricule = (
                "ET"
                + "{:04d}".format(etudiant.compte.pk)
                + etudiant.sexe
                + str(datetime.strptime(etudiant.date_de_naissance, "%d/%m/%Y").year)
                + get_country_code(etudiant.pays)
            )

            etudiant.save()

            return redirect("etudiants:etudiants")

    form = EtudiantCreationForm()
    context = {"etudiants": etudiants, "form": form}
    return render(request, "etudiants/etudiant_list.html", context)


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_staff, login_url="/")
@login_required(login_url="/")
def etudiant_detail_view(request, pk):
    etudiant = get_object_or_404(Etudiant, pk=pk)
    details = Inscription.objects.filter(etudiant=etudiant).order_by("-grade")
    matieres = []

    if details is not None:
        for detail in details:
            modules = Module.objects.filter(
                specialite=detail.specialite, grade=detail.grade
            )
            for module in modules:
                for matiere in Matiere.objects.filter(module=module):
                    if matiere is not None:
                        matieres.append(matiere)

    context = {"etudiant": etudiant, "details": details, "matieres": matieres}
    return render(request, "etudiants/etudiant_detail.html", context)


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_etudiant, login_url="/")
@login_required(login_url="/")
def etudiant_matiere_view(request):
    etudiant = get_object_or_404(Etudiant, pk=request.user.id)
    details = Inscription.objects.filter(etudiant=etudiant).order_by("-grade")
    matieres = []

    if details is not None:
        for detail in details:
            modules = Module.objects.filter(
                specialite=detail.specialite, grade=detail.grade
            )
            for module in modules:
                for matiere in Matiere.objects.filter(module=module):
                    if matiere is not None:
                        matieres.append(matiere)

    context = {"etudiant": etudiant, "details": details, "matieres": matieres}
    return render(request, "etudiants/etudiant_matiere_list.html", context)


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_etudiant, login_url="/")
@login_required(login_url="/")
def etudiant_note_view(request):
    etudiant = get_object_or_404(Etudiant, pk=request.user.id)

    context = {"etudiant": etudiant}
    return render(request, "etudiants/etudiant_note_list.html", context)


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_staff, login_url="/")
@login_required(login_url="/")
def etudiant_inscription_view(request, pk):
    etudiant = get_object_or_404(Etudiant, pk=pk)
    details = Inscription.objects.filter(etudiant=etudiant).order_by("-grade")
    matieres = []

    if request.method == "POST":
        inscription = Inscription()
        specialite = Specialite()

        form = InscriptionForm(request.POST)

        if form.is_valid():
            specialite = form.cleaned_data["specialite"]
            grade = form.cleaned_data["grade"]
            annee = form.cleaned_data["annee"]

            if not Inscription.objects.filter(
                etudiant=etudiant, specialite=specialite, grade=grade, annee=annee
            ).exists():
                inscription.etudiant = etudiant
                inscription.specialite = specialite
                inscription.grade = grade
                inscription.annee = annee
                inscription.save()

            return redirect("etudiants:etudiant", etudiant.pk)

    if details is not None:
        for detail in details:
            modules = Module.objects.filter(
                specialite=detail.specialite, grade=detail.grade
            )
            for module in modules:
                for matiere in Matiere.objects.filter(module=module):
                    if matiere is not None:
                        matieres.append(matiere)

    form = InscriptionForm()
    context = {
        "etudiant": etudiant,
        "details": details,
        "matieres": matieres,
        "form": form,
    }
    return render(request, "etudiants/etudiant_detail.html", context)


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_staff, login_url="/")
@login_required(login_url="/")
def etudiant_update_view(request, pk):
    etudiant = get_object_or_404(Etudiant, pk=pk)
    details = Inscription.objects.filter(etudiant=etudiant).order_by("-grade")
    matieres = []

    form = EtudiantUpdateForm(
        initial={
            "nom": etudiant.nom,
            "prenom": etudiant.prenom,
            "date_de_naissance": etudiant.date_de_naissance,
            "sexe": etudiant.sexe,
            "pays": etudiant.pays,
            "groupe_sanguin": etudiant.groupe_sanguin,
            "telephone": etudiant.compte.telephone,
            "photo": etudiant.compte.telephone,
        }
    )

    if request.method == "POST":
        form = EtudiantUpdateForm(request.POST, request.FILES)

        if form.is_valid():
            compte = etudiant.compte
            compte.telephone = form.cleaned_data["telephone"]
            compte.photo = request.FILES["photo"]
            compte.save()

            etudiant.nom = form.cleaned_data["nom"]
            etudiant.prenom = form.cleaned_data["prenom"]
            etudiant.sexe = form.cleaned_data["sexe"]
            etudiant.date_de_naissance = form.cleaned_data["date_de_naissance"]
            etudiant.pays = form.cleaned_data["pays"]
            etudiant.groupe_sanguin = form.cleaned_data["groupe_sanguin"]

            print(etudiant.nom)

            annee = datetime.strptime(etudiant.date_de_naissance, "%d/%m/%Y").year

            etudiant.matricule = (
                "ET"
                + "{:04d}".format(etudiant.compte.pk)
                + etudiant.sexe
                + str(annee)
                + get_country_code(etudiant.pays)
            )

            etudiant.save()

            return redirect("etudiants:etudiant", etudiant.pk)

    if details is not None:
        for detail in details:
            modules = Module.objects.filter(
                specialite=detail.specialite, grade=detail.grade
            )
            for module in modules:
                for matiere in Matiere.objects.filter(module=module):
                    if matiere is not None:
                        matieres.append(matiere)

    context = {
        "etudiant": etudiant,
        "details": details,
        "matieres": matieres,
        "form": form,
    }
    return render(request, "etudiants/etudiant_detail.html", context)

gestion_scolaire/templates/etudiants/dashboard.html
{% extends "dashboard.html" %}


{% block body %}
{% url "etudiants:ajouter" as add_etudiant_url %}
<div class="container-fluid p-0 mb-3">
	<div class="row row-cols-3 gx-3">
		<div class="col">
			<div class="bg-white p-3 shadow" style="height: 150px;">
				<div class="h4 mb-3">Title</div>
				<div class="h1">200</div>
			</div>
		</div>
		<div class="col">
			<div class="bg-white p-3 shadow" style="height: 150px;">
				<div class="h4 mb-3">Title</div>
				<div class="h1">200</div>
			</div>
		</div>
		<div class="col">
			<div class="bg-white p-3 shadow" style="height: 150px;">
				<div class="h4 mb-3">Title</div>
				<div class="h1">200</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

gestion_scolaire/templates/etudiants/etudiant_detail.html
{% extends "dashboard.html" %}

{% block body %}
{% url "etudiants:etudiant" etudiant.pk as etudiant_detail_url %}
{% url "etudiants:inscription" etudiant.pk as etudiant_inscription_url %}
{% url "etudiants:editer" etudiant.pk as update_etudiant_url %}

<div class="bg-white shadow-sm p-3 mb-3">
	<div class="row row-cols-2 mb-3">
		<div class="col">
			<h2>Informations</h2>
		</div>
		<div class="col-auto ms-auto">
			{% if request.path == etudiant_detail_url %}
			<a class="btn btn-secondary me-2" href="{{ update_etudiant_url }}" role="button">Editer</a>
			<a class="btn btn-secondary ms-1" href="{{ etudiant_inscription_url }}" role="button">Inscrire</a>
			{% else %}
			<a href="{{ etudiant_detail_url }}" class="link-secondary text-decoration-none">Fermer</a>
			{% endif %}
		</div>
	</div>
	<div class="row row-cols-2 m-0" method="POST">
		{% csrf_token %}
		<div class="col-3 p-0 mr-3">
			<img class="img-fluid" src="{{ etudiant.compte.photo.url }}">
		</div>
		<div class="col-9 px-3 py-0">
			<div class="row row-cols-3 border-top border-bottom ms-0 pt-2 h-100">
				<div class="col-4 ps-0">
					<p class="m-0"><small class="h7 text-decoration-none">Matricule</small></p>
					<p class="mb-1 h6">{{ etudiant.matricule }}</p>
					<p class="m-0">Nom</p>
					<p class="mb-1 h6">{{ etudiant.nom }}</p>
					<p class="m-0">Prénom</p>
					<p class="mb-1 h6">{{ etudiant.prenom }}</p>
					<p class="m-0">Pays</p>
					<p class="mb-1 h6">{{ etudiant.pays }}</p>
					<p class="m-0">Sexe</p>
					<p class="mb-1 h6">
						{% if etudiant.sexe == 'M' %}
						Masculin
						{% else %}
						Féminin
						{% endif %}
					</p>
				</div>
				<div class="col-auto">
					<p class="m-0">Date de naissance</p>
					<p class="mb-1 h6">{{ etudiant.date_de_naissance }}</p>
					<p class="m-0">Groupe sanguin</p>
					<p class="mb-1 h6">{{ etudiant.groupe_sanguin }}</p>
					<p class="m-0">Email</p>
					<p class="mb-1 h6">{{ etudiant.compte.email }}</p>
					<p class="m-0">Téléphone</p>
					<p class="mb-1 h6">{{ etudiant.compte.telephone }}</p>
				</div>
			</div>
		</div>
	</div>
	<div class="col-12 mt-3">
		{% if details.count != 0 %}
		<table class="table table-striped table-sm">
			<tbody>
				{% for inscription in details %}
				<tr>
					<td class="h6">{{ inscription.specialite.nom }}</td>
					<td class="h6">{{ inscription.grade }}</td>
					<td class="h6">{{ inscription.annee }}</td>
				</tr>
				{% endfor  %}
			</tbody>
		</table>
		{% endif %}
	</div>
	{% if request.path == etudiant_inscription_url %}
	<form class="row gx-3 mt-3" method="POST">
		{% csrf_token %}
		<div class="col-5">
			<div class="form-floating">
				{{ form.specialite }}
				<label for="floatingInput">Spécialité</label>
			</div>
		</div>
		<div class="col-7">
			<div class="row row-cols-3 gx-3">
				<div class="col">
					<div class="form-floating">
						{{ form.grade }}
						<label for="floatingInput">Grade</label>
					</div>
				</div>
				<div class="col">
					<div class="form-floating">
						{{ form.annee }}
						<label for="floatingInput">Année académique</label>
					</div>
				</div>
				<div class="col">
					<button type="submit" class="btn btn-lg btn-primary w-100 h-100">Inscrire</button>
				</div>
			</div>
		</div>
	</form>
	{% elif request.path == update_etudiant_url %}
	<form class="row g-3" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="col-9">
			<div class="row row-cols-2 gx-3">
				<div class="col">
					<div class="form-floating mb-3 d-flex">
						{{ form.nom }}
						<label for="floatingInput">Nom</label>
					</div>
				</div>
				<div class="col">
					<div class="form-floating mb-3">
						{{ form.prenom }}
						<label for="floatingInput">Prénom</label>
					</div>
				</div>
			</div>
			<div class="row row-cols-3 gx-3">
				<div class="col">
					<div class="form-floating d-flex">
						{{ form.sexe }}
						<label for="floatingInput">Sexe</label>
					</div>
				</div>
				<div class="col">
					<div class="form-floating d-flex">
						{{ form.pays }}
						<label for="floatingInput">Pays</label>
					</div>
				</div>
				<div class="col">
					<div class="form-floating">
						{{ form.telephone }}
						<label for="floatingInput">Téléphone</label>
					</div>
				</div>
			</div>	
		</div>
		<div class="col-3">
			<div class="col-12">
				<div class="form-floating mb-3">
					{{ form.date_de_naissance }}
					<label for="floatingInput">Date de naissance</label>
				</div>
			</div>
			<div class="col-12">
				<div class="form-floating">
					{{ form.groupe_sanguin }}
					<label for="floatingInput">Groupe sanguin</label>
				</div>
			</div>
		</div>
		<div class="col-6">
			{{ form.photo }}
		</div>
		<div class="col-6">
			<button type="submit" class="w-100 stretch btn btn-lg btn-primary">Enregistrer</button>
		</div>
	</form>
	{% endif %}
</div>

{% if matieres %}
<div class="col-12 bg-white shadow-sm p-3">
	<div class="row row-cols-2 mb-3">
		<div class="col">
			<h2>Matières</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-12 table-responsive">
			<table class="table table-striped table-sm">
				<thead>
					<tr>
						<th scope="col">Code</th>
						<th scope="col">Matière</th>
						<th scope="col">Crédit</th>
						<th scope="col">Module</th>
						<th scope="col">Semestre</th>
						<th scope="col">Grade</th>
					</tr>
				</thead>
				<tbody>
					{% for matiere in matieres %}
					<tr>
						<td>{{ matiere.code }}</td>
						<td>{{ matiere.nom }}</td>
						<td>{{ matiere.credit }}</td>
						<td>{{ matiere.module.nom }}</td>
						<td>{{ matiere.module.semestre }}</td>
						<td>{{ matiere.module.grade }}</td>
					</tr>
					{% endfor  %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endif %}


<!-- <div class="col-12 bg-white shadow-sm p-3">
	<div class="row row-cols-2 mb-3">
		<div class="col">
			<h2>Matières en charge</h2>
		</div>
		<div class="col-auto ms-auto">
			{% if request.path == list_enseignant_url %}
			<a class="btn btn-secondary" href="{{ add_enseignant_url }}" role="button">Ajouter</a>
			{% endif %}
		</div>
	</div>
	<div class="row">
		<div class="col-12 table-responsive">
			<table class="table table-striped table-sm">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">Code</th>
						<th scope="col">Matière</th>
						<th scope="col">Crédit</th>
						<th scope="col">Semestre</th>
						<th scope="col">Annéé</th>
					</tr>
				</thead>
				<tbody>
					{% for programme in programmes %}
					
					<tr>
						<td>{{ forloop.counter }}</td>
						<td>{{ programme.matiere.code }}</td>
						<td>{{ programme.matiere.nom }}</td>
						<td>{{ programme.matiere.credit }}</td>
						<td>{{ programme.matiere.module.semestre }}</td>
						<td>{{ programme.annee.annee }}</td>
					</tr>
					{% endfor  %}
				</tbody>
			</table>
		</div>
	</div>
</div> -->
{% endblock %}

gestion_scolaire/templates/etudiants/etudiant_matiere_list.html
{% extends "dashboard.html" %}


{% block body %}

{% url "etudiants:ajouter" as add_etudiant_url %}
{% url "etudiants:etudiants" as list_etudiant_url %}


<div class="col-12 bg-white shadow-sm p-3">
	<div class="row row-cols-2 mb-3">
		<div class="col">
			<h2>Mes matières</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-12 table-responsive">
			<table class="table table-striped table-sm">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">Code</th>
						<th scope="col">Matière</th>
						<th scope="col">Crédit</th>
						<th scope="col">Semestre</th>
						<th scope="col">Grade</th>
					</tr>
				</thead>
				<tbody>
					{% for matiere in matieres %}
					<tr>
						<td>{{ forloop.counter }}</td>
						<td>{{ matiere.code }}</td>
						<td>{{ matiere.nom }}</td>
						<td>{{ matiere.credit }}</td>
						<td>{{ matiere.module.semestre }}</td>
						<td>{{ matiere.module.grade }}</td>
					</tr>
					{% endfor  %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}