gestion_scolaire/comptes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import login_view, logout_view, activate_account_view, set_password_view, profil_detail_view

app_name = "comptes"
urlpatterns = [
    path("", login_view, name="login"),
    path("deconnexion", logout_view, name="logout"),
    path("profil/", profil_detail_view, name="profil"),
    path("activate/<uidb64>/<token>/", activate_account_view, name="activate"),
    path("set-password/<uidb64>/<token>/", set_password_view, name="set_password"),
]

gestion_scolaire/cours/urls.py
from django.urls import path

from .views import (
    create_module,
    module_list_view,
    create_matiere,
    matiere_list_view,
    cours_dashboard_view,
    matiere_detail_view,
    matiere_view,
)


app_name = "cours"
urlpatterns = [
    path("modules/ajouter", module_list_view, name="ajouter_module"),
    path("modules", module_list_view, name="modules"),
    path("matieres/ajouter", matiere_list_view, name="ajouter_matiere"),
    path("matieres", matiere_list_view, name="matieres"),
    path("tableau-de-bord", cours_dashboard_view, name="dashboard"),
    path("mesma", matiere_view, name="mat"),
    path("matieres/<int:pk>/", matiere_detail_view, name="matiere"),
]

gestion_scolaire/gestion_scolaire/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("comptes.urls")),
    path("staffs/", include("staffs.urls")),
    path("parcours/", include("parcours.urls")),
    path("cours/", include("cours.urls")),
    path("enseignants/", include("enseignants.urls")),
    path("etudiants/", include("etudiants.urls")),
    path("evaluations/", include("notes.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion_scolaire/notes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (
    evaluation_create_view,
    evaluation_list_view,
    evaluation_note_create_view,
)

app_name = "notes"
urlpatterns = [
    path("<int:pk>/ajouter", evaluation_create_view, name="ajouter"),
    path("<int:pk>/", evaluation_list_view, name="evaluations"),
    path("<int:pk>/notes/", evaluation_note_create_view, name="notes"),
]

gestion_scolaire/parcours/urls.py
from django.urls import path

from .views import (
    create_domain,
    domain_list_view,
    create_mention,
    mention_list_view,
    create_specialite,
    specialite_list_view,
    dashboard_view,
)

app_name = "parcours"
urlpatterns = [
    path("domaines/ajouter", domain_list_view, name="ajouter_domain"),
    path("domaines", domain_list_view, name="domains"),
    path("mentions/ajouter", mention_list_view, name="ajouter_mention"),
    path("mentions", mention_list_view, name="mentions"),
    path("specialites/ajouter", specialite_list_view, name="ajouter_specialite"),
    path("specialites", specialite_list_view, name="specialites"),
    path("", dashboard_view, name="dashboard"),
]

gestion_scolaire/staffs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (
    staff_create_view,
    staff_list_view,
    staff_detail_view,
    staff_dashboard_view,
)

app_name = "staffs"
urlpatterns = [
    path("ajouter", staff_list_view, name="ajouter"),
    path("", staff_list_view, name="staffs"),
    path("<int:pk>/", staff_detail_view, name="staff"),
    path("tableau-de-bord", staff_dashboard_view, name="dashboard"),
]

gestion_scolaire/templates/base.html
<!doctype html>
	<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- Bootstrap CSS -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.1.4/dist/css/datepicker.min.css'>   

		<title>Hello, world!</title>
		<style type="text/css">
			.bd-placeholder-img {
				font-size: 1.125rem;
				text-anchor: middle;
				-webkit-user-select: none;
				-moz-user-select: none;
				user-select: none;
			}

			@media (min-width: 768px) {
				.bd-placeholder-img-lg {
					font-size: 3.5rem;
				}
			}

			.form-floating > .bi-calendar-date + .datepicker_input + label {
				padding-left: 3.5rem;
				z-index: 3;
			}
		</style>
	</head>
	<body>
		{% url "comptes:login" as login_url %}

		{% block content %} {% endblock %}


		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

		<script src='https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.1.4/dist/js/datepicker-full.min.js'></script>
		
		<script type="text/javascript">
			function edit(el) {
				el.childNodes[1].removeAttribute("disabled");
				el.childNodes[1].style.backgroundColor = "white";
				el.childNodes[1].focus();
				window.getSelection().removeAllRanges();
			}
			function disable(el) {
				el.style.backgroundColor = "inherit";
			}

			const getDatePickerTitle = elem => {

				const label = elem.nextElementSibling;
				let titleText = '';
				if (label && label.tagName === 'LABEL') {
					titleText = label.textContent;
				} else {
					titleText = elem.getAttribute('aria-label') || '';
				}
				return titleText;
			}

			const elems = document.querySelectorAll('.datepicker_input');
			for (const elem of elems) {
				const datepicker = new Datepicker(elem, {
					'format': 'dd/mm/yyyy',
					title: getDatePickerTitle(elem)
				});
			}
		</script>
		{% if request.path == login_url or 'set_password' in request.path %}
		<script type="text/javascript">
			var viewportHeight = self.innerHeight
			var navbarHeight = document.getElementById("navbar").offsetHeight
			var boxWidth = document.getElementById("center").offsetWidth
			document.getElementById("login").style.height = (viewportHeight - navbarHeight) + "px"
			document.getElementById("center").style.height = boxWidth + "px"
		</script>
		{% elif 'password' in request.path %}
		<script type="text/javascript">
			var viewportHeight = self.innerHeight
			var navbarHeight = document.getElementById("navbar").offsetHeight
			var boxWidth = document.getElementById("center").offsetWidth
			document.getElementById("login").style.height = (viewportHeight - navbarHeight) + "px"
			document.getElementById("center").style.height = boxWidth + "px"
		</script>
		{% else %}
		<script type="text/javascript">
			document.getElementById("sidebarHeight").style.height = self.innerHeight + "px"
		</script>
		{% endif %}
	</body>
	</html>

gestion_scolaire/templates/dashboard.html
{% extends "base.html" %}

{% block content %}
{% url "parcours:ajouter_domain" as add_domain_url %}
{% url "parcours:ajouter_mention" as add_mention_url %}
{% url "parcours:ajouter_specialiter" as add_domain_url %}
{% url "parcours:domains" as list_domain_url %}
{% url "parcours:mentions" as list_mention_url %}
{% url "parcours:specialites" as list_specialite_url %}
{% url "parcours:dashboard" as parcours_dashboard_url %}

{% url "cours:modules" as list_module_url %}
{% url "cours:matieres" as list_matiere_url %}
{% url "cours:ajouter_module" as add_module_url %}
{% url "cours:ajouter_matiere" as add_matiere_url %}
{% url "cours:dashboard" as cours_dashboard_url %}

{% url "enseignants:enseignants" as list_enseignant_url %}
{% url "enseignants:ajouter" as add_enseignant_url %}
{% url "enseignants:enseignant" enseignant.pk as enseignant_detail_url %}

{% url "etudiants:etudiants" as list_etudiant_url %}
{% url "etudiants:ajouter" as add_etudiant_url %}
{% url "etudiants:etudiant" as detail_etudiant_url %}

<div class="container-fluid" style="background-color: #E4E7E9;">
	<div class="row row-cols-2">
		<div class="col-2 col-lg-3 p-0">
			{% include 'sidebar.html' %}
		</div>
		<div class="col-10 col-lg-9">
			<div class="row sticky-top bg-white" style="height: 70px;">
				<div class="col-auto d-flex px-3">
					<div class="row align-items-center">
						{% if request.user.type_de_compte == 'ST' %}
						{% if 'parcours' in request.path %}
						<a class="col text-decoration-none {% if not 'domaines' in request.path %}text-secondary{% endif %}" href="{{ list_domain_url }}">Domaines</a>
						<a class="col text-decoration-none {% if not 'mentions' in request.path %}text-secondary{% endif %}" href="{{ list_mention_url }}">Mentions</a>
						<a class="col text-decoration-none {% if not 'specialites' in request.path %}text-secondary{% endif %}" href="{{ list_specialite_url }}">Spécialités</a>
						{% elif '/cours' in request.path %}
						<a class="col text-decoration-none {% if not 'modules' in request.path %}text-secondary{% endif %}" href="{{ list_module_url }}">Modules</a>
						<a class="col text-decoration-none {% if not 'matieres' in request.path %}text-secondary{% endif %}" href="{{ list_matiere_url }}">Matières</a>
						{% else %}
						
						{% endif %}
						{% endif %}


						
					</div>
				</div>
				<div class='col-auto ms-auto d-flex align-items-center px-3'>
					<span class='col mx-3'>Bienvenu, 
						<strong>
						{% if request.user.type_de_compte == 'AD' %}
						{{ request.user.staff.prenom }}
						{% elif request.user.type_de_compte == 'ST' %}
						{{ request.user.staff.prenom }}
						{% elif request.user.type_de_compte == 'EN' %}
						{{ request.user.enseignant.prenom }}
						{% else %}
						{{ request.user.etudiant.prenom }}
						{% endif %}
						</strong>
					</span>
					<img class="img-fluid rounded-pill" src="{{ request.user.photo.url }}" width="40">
				</div>
			</div>
			<div class="row p-3">
				{% block body %} {% endblock %}
			</div>
		</div>
	</div>
</div>

{% endblock %}

gestion_scolaire/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbar" style="--bs-bg-opacity: .100;" >
	<div class="container-fluid">
		<a class="navbar-brand" href="">Collecte de notes</a> 
	</div>
</nav>

gestion_scolaire/templates/sidebar.html
{% url "comptes:login" as login_url %}
{% url "comptes:logout" as logout_url %}
{% url "comptes:profil" as profil_url %}

{% url "staffs:ajouter" as add_staff_url %}
{% url "staffs:staffs" as list_staff_url %}
{% url "staffs:dashboard" as staff_dashboard_url %}

{% url "parcours:domains" as list_domain_url %}
{% url "parcours:ajouter_domain" as add_domain_url %}

{% url "parcours:mentions" as list_mention_url %}
{% url "parcours:ajouter_mention" as add_mention_url %}
{% url "parcours:specialites" as list_specialite_url %}
{% url "parcours:ajouter_specialite" as add_specialite_url %}
{% url "parcours:dashboard" as parcours_dashboard_url %}

{% url "cours:modules" as list_module_url %}
{% url "cours:ajouter_module" as add_module_url %}
{% url "cours:matieres" as list_matiere_url %}
{% url "cours:ajouter_matiere" as add_matiere_url %}
{% url "cours:dashboard" as cours_dashboard_url %}

{% url "enseignants:enseignants" as list_enseignant_url %}
{% url "enseignants:ajouter" as add_enseignant_url %}
{% url "enseignants:enseignant" as detail_enseignant_url %}
{% url "enseignants:dashboard" as enseignant_dashboard_url %}
{% url "enseignants:matieres" as enseignant_matiere_url %}

{% url "etudiants:etudiants" as list_etudiant_url %}
{% url "etudiants:ajouter" as add_etudiant_url %}
{% url "etudiants:etudiant" as detail_etudiant_url %}
{% url "etudiants:matieres" as etudiant_matiere_url %}
{% url "etudiants:notes" as etudiant_note_url %}

{% url "notes:evaluations" request.user.pk as enseignant_evaluation_url %}

<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark sticky-top" id="sidebarHeight">
	<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
		<a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
			<h1 class="h2">Collecte de note</h1>
		</a>
		
	</div>
	<ul class="nav nav-pills flex-column mb-auto">
		{% if request.user.type_de_compte == 'AD' %}
		<li>
			<a href="{{ list_staff_url }}" class="nav-link text-white {% if 'staffs' in request.path %}active{% endif %}">
				Staffs
			</a>
		</li>
		{% elif request.user.type_de_compte == 'ST' %}
		<li>
			<a href="{{ list_etudiant_url }}" class="nav-link text-white {% if 'etudiants' in request.path %}active{% endif %}">
				Etudiants
			</a>
		</li>
		<li>
			<a href="{{ list_domain_url }}" class="nav-link text-white {% if 'parcours' in request.path %}active{% endif %}">
				Parcours
			</a>
		</li>
		<li>
			<a href="{{ list_enseignant_url }}" class="nav-link text-white {% if 'enseignants' in request.path %}active{% endif %}">
				Enseignants
			</a>
		</li>
		<li>
			<a href="{{ list_matiere_url }}" class="nav-link text-white {% if 'parcours' in request.path %}{% elif 'cours' in request.path %}active{% else %}{% endif %}">
				Cours
			</a>
		</li>
		{% elif request.user.type_de_compte == 'EN' %}
		<li>
			<a href="{{ enseignant_matiere_url }}" class="nav-link text-white {% if 'matieres' in request.path %}active{% endif %}">
				Matières
			</a>
		</li>
		<li>
			<a href="{{ enseignant_evaluation_url }}" class="nav-link text-white {% if 'evaluations' in request.path %}active{% endif %}">
				Evaluations
			</a>
		</li>
		{% elif request.user.type_de_compte == 'ET' %}
		<li>
			<a href="{{ etudiant_matiere_url }}" class="nav-link text-white {% if 'matieres' in request.path %}active{% endif %}">
				Mes matières
			</a>
		</li>
		<li>
			<a href="{{ etudiant_note_url }}" class="nav-link text-white {% if 'notes' in request.path %}active{% endif %}">
				Mes notes
			</a>
		</li>
		{% else %}
		{% endif %}
		<li>
			<a href="{{ profil_url }}" class="nav-link text-white {% if 'profil' in request.path %}active{% endif %}">
				Mon Profil
			</a>
		</li>
	</ul>
	<hr>
	<div class="">
		{% if request.user.is_authenticated %}
		<a class="w-100 btn btn-secondary" href="{{ logout_url }}" role="button">Déconnexion</a>
		{% endif %}
	</div>
</div>