gestion_scolaire/cours/urls.py
from django.urls import path

from .views import (
    create_module,
    module_list_view,
    create_matiere,
    matiere_list_view,
    cours_dashboard_view,
    matiere_detail_view,
    matiere_view,
)


app_name = "cours"
urlpatterns = [
    path("modules/ajouter", module_list_view, name="ajouter_module"),
    path("modules", module_list_view, name="modules"),
    path("matieres/ajouter", matiere_list_view, name="ajouter_matiere"),
    path("matieres", matiere_list_view, name="matieres"),
    path("tableau-de-bord", cours_dashboard_view, name="dashboard"),
    path("mesma", matiere_view, name="mat"),
    path("matieres/<int:pk>/", matiere_detail_view, name="matiere"),
]

gestion_scolaire/enseignants/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (
    enseignant_create_view,
    enseignant_list_view,
    enseignant_dashboard_view,
    enseignant_detail_view,
    enseignant_update_view,
    enseignant_matiere_list_view,
)

app_name = "enseignants"
urlpatterns = [
    path("ajouter/", enseignant_list_view, name="ajouter"),
    path("", enseignant_list_view, name="enseignants"),
    path("dashboard/", enseignant_dashboard_view, name="dashboard"),
    path("matieres/", enseignant_matiere_list_view, name="matieres"),
    path("<int:pk>/", enseignant_detail_view, name="enseignant"),
    path("<int:pk>/modifier/", enseignant_update_view, name="editer"),
]

gestion_scolaire/gestion_scolaire/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("comptes.urls")),
    path("staffs/", include("staffs.urls")),
    path("parcours/", include("parcours.urls")),
    path("cours/", include("cours.urls")),
    path("enseignants/", include("enseignants.urls")),
    path("etudiants/", include("etudiants.urls")),
    path("evaluations/", include("notes.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion_scolaire/enseignants/models.py
from django.db import models

from comptes.models import Compte, Information


class Enseignant(Information):
    compte = models.OneToOneField(
        Compte, primary_key=True, on_delete=models.CASCADE, related_name="enseignant"
    )

    def __str__(self):
        return self.nom + " " + self.prenom

gestion_scolaire/enseignants/forms.py
from django import forms

from pays import Countries

from cours.models import Matiere
from comptes.models import SEXES

from .models import Enseignant

PAYS = list()

for country in Countries():
    PAYS.append((country.name, country.name))


class EnseignantCreationForm(forms.Form):
    nom = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Nom",
            }
        ),
        max_length=255,
    )
    prenom = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Prénom",
            }
        ),
        max_length=255,
    )
    date_de_naissance = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "datepicker_input form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "JJ/MM/AAAA",
            }
        ),
        max_length=255,
    )
    sexe = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Sexe",
            }
        ),
        choices=SEXES,
    )
    pays = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Sexe",
            }
        ),
        choices=PAYS,
    )
    photo = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                "class": "form-control form-control-lg shadow-none",
                "id": "formFileLg",
                "placeholder": "Email",
            }
        ),
        max_length=255,
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Email",
            }
        ),
        max_length=255,
    )
    telephone = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Téléphone",
            }
        ),
        max_length=255,
    )


class EnseignantUpdateForm(forms.Form):
    nom = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Nom",
            }
        ),
        max_length=255,
    )
    prenom = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Prénom",
            }
        ),
        max_length=255,
    )
    date_de_naissance = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "datepicker_input form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "JJ/MM/AAAA",
            }
        ),
        max_length=255,
    )
    sexe = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Sexe",
            }
        ),
        choices=SEXES,
    )
    pays = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Sexe",
            }
        ),
        choices=PAYS,
    )
    photo = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                "class": "form-control form-control-lg shadow-none",
                "id": "formFileLg",
                "placeholder": "Email",
            }
        ),
        max_length=255,
    )
    telephone = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Téléphone",
            }
        ),
        max_length=255,
    )

gestion_scolaire/enseignants/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db import transaction
from django.contrib.auth.decorators import login_required, user_passes_test

from datetime import datetime

from comptes.models import Compte, get_country_code
from staffs.views import is_staff, is_not_anonymous, is_enseignant
from cours.models import Attribution
from notes.models import Evaluation, Note
from etudiants.models import Inscription

from .models import Enseignant
from .forms import EnseignantCreationForm, EnseignantUpdateForm


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_staff, login_url="/")
@login_required(login_url="/")
@transaction.atomic
def enseignant_create_view(request):
    if request.method == "POST":
        form = EnseignantCreationForm(request.POST)
        if form.is_valid():
            nom = form.cleaned_data["nom"]
            prenom = form.cleaned_data["prenom"]
            sexe = form.cleaned_data["sexe"]
            telephone = form.cleaned_data["telephone"]
            email = form.cleaned_data["email"]
            # type_de_compte = form.cleaned_data['type_de_compte']
            # photo = form.cleaned_data['photo']

            compte = Compte.objects.create_user(
                email=email,
                telephone=telephone,
                password="1234",
                type_de_compte="EN",
            )

            enseignant = Enseignant.objects.create(
                compte=compte, nom=nom, prenom=prenom, sexe=sexe
            )

            return redirect("enseignants:enseignants")

    form = EnseignantCreationForm()
    return render(request, "enseignants/enseignant_creation.html", {"form": form})


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_staff, login_url="/")
@login_required(login_url="/")
@transaction.atomic
def enseignant_list_view(request):
    queryset = Enseignant.objects.all()

    if request.method == "POST":
        compte = Compte()
        enseignant = Enseignant()
        form = EnseignantCreationForm(request.POST, request.FILES)
        if form.is_valid():
            compte.telephone = form.cleaned_data["telephone"]
            compte.email = form.cleaned_data["email"]
            compte.photo = request.FILES["photo"]
            compte.type_de_compte = "EN"
            compte.set_password("1234")
            compte.save()

            enseignant.compte = compte
            enseignant.nom = form.cleaned_data["nom"]
            enseignant.prenom = form.cleaned_data["prenom"]
            enseignant.sexe = form.cleaned_data["sexe"]
            enseignant.date_de_naissance = form.cleaned_data["date_de_naissance"]
            enseignant.pays = form.cleaned_data["pays"]

            annee_de_naissance = datetime.strptime(
                enseignant.date_de_naissance, "%d/%m/%Y"
            ).year

            enseignant.matricule = (
                "EN"
                + "{:04d}".format(enseignant.compte.pk)
                + enseignant.sexe
                + str(annee_de_naissance)
                + get_country_code(enseignant.pays)
            )

            enseignant.save()

            return redirect("enseignants:enseignants")

    form = EnseignantCreationForm()
    context = {"enseignants": queryset, "form": form}
    return render(request, "enseignants/enseignant_list.html", context)


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_staff, login_url="/")
@login_required(login_url="/")
def enseignant_detail_view(request, pk):
    enseignant = get_object_or_404(Enseignant, pk=pk)
    matieres = Attribution.objects.filter(enseignant=enseignant)

    context = {"enseignant": enseignant, "programmes": matieres}
    return render(request, "enseignants/enseignant_detail.html", context)


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_enseignant, login_url="/")
@login_required(login_url="/")
def enseignant_matiere_list_view(request):
    enseignant = get_object_or_404(Enseignant, pk=request.user.pk)
    matieres = Attribution.objects.filter(enseignant=enseignant)

    context = {"enseignant": enseignant, "programmes": matieres}
    return render(request, "cours/matiere_list.html", context)


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_staff, login_url="/")
@login_required(login_url="/")
def enseignant_update_view(request, pk):
    enseignant = get_object_or_404(Enseignant, pk=pk)
    attributions = Attribution.objects.filter()

    form = EnseignantUpdateForm(
        initial={
            "nom": enseignant.nom,
            "prenom": enseignant.prenom,
            "date_de_naissance": enseignant.date_de_naissance,
            "sexe": enseignant.sexe,
            "pays": enseignant.pays,
            "telephone": enseignant.compte.telephone,
        }
    )

    if request.method == "POST":
        form = EnseignantUpdateForm(request.POST, request.FILES)

        if form.is_valid():
            compte = enseignant.compte
            compte.telephone = form.cleaned_data["telephone"]
            compte.photo = request.FILES["photo"]
            compte.save()

            enseignant.nom = form.cleaned_data["nom"]
            enseignant.prenom = form.cleaned_data["prenom"]
            enseignant.sexe = form.cleaned_data["sexe"]
            enseignant.date_de_naissance = form.cleaned_data["date_de_naissance"]
            enseignant.pays = form.cleaned_data["pays"]

            annee = datetime.strptime(enseignant.date_de_naissance, "%d/%m/%Y").year

            enseignant.matricule = (
                "EN"
                + "{:04d}".format(enseignant.compte.pk)
                + enseignant.sexe
                + str(annee)
                + get_country_code(enseignant.pays)
            )

            enseignant.save()

            return redirect("enseignants:enseignant", enseignant.pk)

    context = {"enseignant": enseignant, "programmes": attributions, "form": form}
    return render(request, "enseignants/enseignant_detail.html", context)


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_staff, login_url="/")
@login_required(login_url="/")
def enseignant_dashboard_view(request):
    queryset = Enseignant.objects.all()
    context = {"enseignant": queryset}
    return render(request, "enseignants/dashboard.html", context)

gestion_scolaire/templates/enseignants/dashboard.html
{% extends "dashboard.html" %}


{% block body %}
{% url "enseignants:ajouter" as add_enseignant_url %}
<div class="container-fluid p-0 mb-3">
	<div class="row row-cols-3 gx-3">
		<div class="col">
			<div class="bg-white p-3 shadow" style="height: 150px;">
				<div class="h4 mb-3">Title</div>
				<div class="h1">200</div>
			</div>
		</div>
		<div class="col">
			<div class="bg-white p-3 shadow" style="height: 150px;">
				<div class="h4 mb-3">Title</div>
				<div class="h1">200</div>
			</div>
		</div>
		<div class="col">
			<div class="bg-white p-3 shadow" style="height: 150px;">
				<div class="h4 mb-3">Title</div>
				<div class="h1">200</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

gestion_scolaire/templates/enseignants/enseignant_creation.html
{% extends "dashboard.html" %}

{% block body %}
<div class="bg-white shadow-sm p-3">
	<div class="row mb-3">
		<h2>Ajouter un enseignant</h2>
	</div>
	<form class="row row-cols-2 g-3" method="POST">
		{% csrf_token %}
		<div class="col">
			<div class="form-floating mb-3">
				{{ form.nom }}
				<label for="floatingInput">Nom</label>
			</div>
			<div class="form-floating mb-3">
				{{ form.sexe }}
				<label for="floatingInput">Sexe</label>
			</div>
			<div class="form-floating mb-3">
				{{ form.email }}
				<label for="floatingInput">Adresse email</label>
			</div>
		</div>

		<div class="col">
			<div class="form-floating mb-3">
				{{ form.prenom }}
				<label for="floatingInput">Prénom</label>
			</div>
			<div class="form-floating mb-3">
				{{ form.telephone }}
				<label for="floatingInput">Téléphone</label>
			</div>
			<button type="submit" class="w-100 stretch btn btn-lg btn-primary">Enregistrer</button>
		</div>
	</form>
</div>
{% endblock %}

gestion_scolaire/templates/enseignants/enseignant_detail.html
{% extends "dashboard.html" %}


{% block body %}
{% url "enseignants:enseignant" enseignant.pk as enseignant_detail_url %}
{% url "enseignants:editer" enseignant.pk as update_enseignant_url %}
<div class="bg-white shadow-sm p-3 mb-3">
	<div class="row row-cols-2 mb-3">
		<div class="col">
			<h2>Informations</h2>
		</div>
		<div class="col-auto ms-auto">
			{% if request.path == enseignant_detail_url %}
			<a class="btn btn-secondary" href="{{ update_enseignant_url }}" role="button">Editer</a>
			{% else %}
			<a href="{{ enseignant_detail_url }}" class="link-secondary text-decoration-none">Fermer</a>
			{% endif %}
		</div>
	</div>
	<div class="row row-cols-2 m-0" method="POST">
		{% csrf_token %}
		<div class="col-3 p-0 mr-3">
			<img class="img-fluid" src="{{ enseignant.compte.photo.url }}">
		</div>
		<div class="col-9 px-3 py-0">
			<div class="row row-cols-3 border-top border-bottom ms-0 pt-2 h-100">
				<div class="col-4 ps-0">
					<p class="m-0"><small class="h7 text-decoration-none">Matricule</small></p>
					<p class="mb-2 h6">{{ enseignant.matricule }}</p>
					<p class="m-0">Nom</p>
					<p class="mb-2 h6">{{ enseignant.nom }}</p>
					<p class="m-0">Prénom</p>
					<p class="mb-2 h6">{{ enseignant.prenom }}</p>
					<p class="m-0">pays</p>
					<p class="mb-2 h6">{{ enseignant.pays }}</p>
				</div>
				<div class="col-auto">
					<p class="m-0">Sexe</p>
					<p class="mb-2 h6">
						{% if enseignant.sexe == 'M' %}
						Masculin
						{% else %}
						Féminin
						{% endif %}
					</p>
					<p class="m-0">Date de naissance</p>
					<p class="mb-2 h6">{{ enseignant.date_de_naissance }}</p>
					<p class="m-0">Email</p>
					<p class="mb-2 h6">{{ enseignant.compte.email }}</p>
					<p class="m-0">Téléphone</p>
					<p class="mb-2 h6">{{ enseignant.compte.telephone }}</p>
				</div>
			</div>
		</div>
	</div>
	{% if request.path == update_enseignant_url %}
	<form class="row row-cols-2 g-3 mt-3" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="col">
			<div class="form-floating mb-3">
				{{ form.nom }}
				<label for="floatingInput">Nom</label>
			</div>
			<div class="row row-cols-2 gx-3">
				<div class="col">
					<div class="form-floating mb-3 d-flex">
						{{ form.date_de_naissance }}
						<label for="floatingInput">Date de naissance</label>
					</div>
				</div>
				<div class="col">
					<div class="form-floating mb-3">
						{{ form.sexe }}
						<label for="floatingInput">Sexe</label>
					</div>
				</div>
			</div>
			<div>
				{{ form.photo }}
			</div>
		</div>
		<div class="col">
			<div class="form-floating mb-3">
				{{ form.prenom }}
				<label for="floatingInput">Prénom</label>
			</div>
			<div class="row row-cols-2 gx-3">
				<div class="col">
					<div class="form-floating mb-3 d-flex">
						{{ form.pays }}
						<label for="floatingInput">Pays</label>
					</div>
				</div>
				<div class="col">
					<div class="form-floating mb-3">
						{{ form.telephone }}
						<label for="floatingInput">Téléphone</label>
					</div>
				</div>
			</div>
			<button type="submit" class="w-100 stretch btn btn-lg btn-primary">Enregistrer</button>
		</div>
	</form>
	{% endif %}
</div>

<div class="col-12 bg-white shadow-sm p-3">
	<div class="row row-cols-2 mb-3">
		<div class="col">
			<h2>Matières en charge</h2>
		</div>
		<div class="col-auto ms-auto">
			{% if request.path == list_enseignant_url %}
			<a class="btn btn-secondary" href="{{ add_enseignant_url }}" role="button">Ajouter</a>
			{% endif %}
		</div>
	</div>
	<div class="row">
		<div class="col-12 table-responsive">
			<table class="table table-striped table-sm">
				<thead>
					<tr>
						<th scope="col">Code</th>
						<th scope="col">Matière</th>
						<th scope="col">Crédit</th>
						<th scope="col">Semestre</th>
						<th scope="col">Grade</th>
						<th scope="col">Année</th>
					</tr>
				</thead>
				<tbody>
					{% for programme in programmes %}
					
					<tr>
						<td>{{ programme.matiere.code }}</td>
						<td>{{ programme.matiere.nom }}</td>
						<td>{{ programme.matiere.credit }}</td>
						<td>{{ programme.matiere.module.semestre }}</td>
						<td>{{ programme.matiere.module.grade }}</td>
						<td>{{ programme.annee }}</td>
					</tr>
					{% endfor  %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

gestion_scolaire/templates/enseignants/enseignant_list.html
{% extends "dashboard.html" %}


{% block body %}

{% url "enseignants:ajouter" as add_enseignant_url %}
{% url "enseignants:enseignants" as list_enseignant_url %}
{% url "enseignants:enseignants" as list_enseignant_url %}

{% if request.path == add_enseignant_url %}
<div class="col-12 bg-white shadow-sm p-3 pb-4 mb-3">
	<div class="row row-cols-2 mb-4">
		<div class="col">
			<h2 id="">Ajouter un enseignant</h2>
		</div>
		<div class="col-auto ms-auto">
			<a href="{{ list_enseignant_url }}" class="link-secondary text-decoration-none">Fermer</a>
		</div>
	</div>
	<form class="row row-cols-2 g-3" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="col">
			<div class="form-floating mb-3">
				{{ form.nom }}
				<label for="floatingInput">Nom</label>
			</div>
			<div class="row row-cols-2 gx-3">
				<div class="col">
					<div class="form-floating mb-3 d-flex">
						{{ form.date_de_naissance }}
						<label for="floatingInput">Date de naissance</label>
					</div>
				</div>
				<div class="col">
					<div class="form-floating mb-3">
						{{ form.sexe }}
						<label for="floatingInput">Sexe</label>
					</div>
				</div>
			</div>
			<div class="form-floating mb-3">
				{{ form.email }}
				<label for="floatingInput">Adresse email</label>
			</div>
			
			<button type="submit" class="w-100 stretch btn btn-lg btn-primary">Enregistrer</button>
		</div>
		<div class="col">
			<div class="form-floating mb-3">
				{{ form.prenom }}
				<label for="floatingInput">Prénom</label>
			</div>
			<div class="form-floating mb-3">
				{{ form.pays }}
				<label for="floatingInput">Pays</label>
			</div>
			<div class="form-floating mb-3">
				{{ form.telephone }}
				<label for="floatingInput">Téléphone</label>
			</div>
			<div>
				{{ form.photo }}
			</div>
		</div>
	</form>
</div>
{% endif %}

<div class="col-12 bg-white shadow-sm p-3">
	<div class="row row-cols-2 mb-3">
		<div class="col">
			<h2>Liste d'enseignants</h2>
		</div>
		<div class="col-auto ms-auto">
			{% if request.path == list_enseignant_url %}
			<a class="btn btn-secondary" href="{{ add_enseignant_url }}" role="button">Ajouter</a>
			{% endif %}
		</div>
	</div>
	<div class="row">
		<div class="col-12 table-responsive">
			<table class="table table-striped table-sm">
				<thead>
					<tr>
						<th scope="col">Matricule</th>
						<th scope="col">Nom</th>
						<th scope="col">Prénom</th>
						<th scope="col">Pays</th>
						<th scope="col">Sexe</th>
						<th scope="col">Téléphone</th>
						<th scope="col"></th>
					</tr>
				</thead>
				<tbody>
					{% for enseignant in enseignants %}
					
					<tr>
						<td>{{ enseignant.matricule }}</td>
						<td>{{ enseignant.nom }}</td>
						<td>{{ enseignant.prenom }}</td>
						<td>{{ enseignant.pays }}</td>
						<td>{{ enseignant.sexe }}</td>
						<td>{{ enseignant.compte.telephone }}</td>
						<td>
							<a href="{% url 'enseignants:enseignant' enseignant.pk %}" class="text-decoration-none">Détail</a>
						</td>
					</tr>
					{% endfor  %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}