gestion_scolaire/cours/urls.py
from django.urls import path

from .views import (
    create_module,
    module_list_view,
    create_matiere,
    matiere_list_view,
    cours_dashboard_view,
    matiere_detail_view,
    matiere_view,
)


app_name = "cours"
urlpatterns = [
    path("modules/ajouter", module_list_view, name="ajouter_module"),
    path("modules", module_list_view, name="modules"),
    path("matieres/ajouter", matiere_list_view, name="ajouter_matiere"),
    path("matieres", matiere_list_view, name="matieres"),
    path("tableau-de-bord", cours_dashboard_view, name="dashboard"),
    path("mesma", matiere_view, name="mat"),
    path("matieres/<int:pk>/", matiere_detail_view, name="matiere"),
]

gestion_scolaire/gestion_scolaire/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("comptes.urls")),
    path("staffs/", include("staffs.urls")),
    path("parcours/", include("parcours.urls")),
    path("cours/", include("cours.urls")),
    path("enseignants/", include("enseignants.urls")),
    path("etudiants/", include("etudiants.urls")),
    path("evaluations/", include("notes.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion_scolaire/notes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (
    evaluation_create_view,
    evaluation_list_view,
    evaluation_note_create_view,
)

app_name = "notes"
urlpatterns = [
    path("<int:pk>/ajouter", evaluation_create_view, name="ajouter"),
    path("<int:pk>/", evaluation_list_view, name="evaluations"),
    path("<int:pk>/notes/", evaluation_note_create_view, name="notes"),
]

gestion_scolaire/parcours/urls.py
from django.urls import path

from .views import (
    create_domain,
    domain_list_view,
    create_mention,
    mention_list_view,
    create_specialite,
    specialite_list_view,
    dashboard_view,
)

app_name = "parcours"
urlpatterns = [
    path("domaines/ajouter", domain_list_view, name="ajouter_domain"),
    path("domaines", domain_list_view, name="domains"),
    path("mentions/ajouter", mention_list_view, name="ajouter_mention"),
    path("mentions", mention_list_view, name="mentions"),
    path("specialites/ajouter", specialite_list_view, name="ajouter_specialite"),
    path("specialites", specialite_list_view, name="specialites"),
    path("", dashboard_view, name="dashboard"),
]

gestion_scolaire/cours/models.py
from django.db import models

from parcours.models import Specialite
from enseignants.models import Enseignant


GRADES = (
    ("L1", "Licence 1"),
    ("L2", "Licence 2"),
    ("L3", "Licence 3"),
    ("M1", "Master 1"),
    ("M2", "Master 2"),
)


SEMESTRES = (
    ("S1", "Semestre 1"),
    ("S2", "Semestre 2"),
)


class Module(models.Model):
    specialite = models.ForeignKey(Specialite, on_delete=models.CASCADE, related_name="modules")
    grade = models.CharField(max_length=20, choices=GRADES)
    semestre = models.CharField(max_length=20, choices=SEMESTRES)
    code = models.CharField(max_length=20)
    nom = models.CharField(max_length=255)

    def __str__(self):
        return (
            self.nom
            + " --> "
            + self.semestre
            + " - "
            + self.grade
            + " - "
            + self.specialite.sigle
        )


class Matiere(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE, related_name="matieres")
    code = models.CharField(max_length=20)
    nom = models.CharField(max_length=255)
    credit = models.CharField(max_length=20)

    def __str__(self):
        return self.nom


class Attribution(models.Model):
    enseignant = models.ForeignKey(Enseignant, on_delete=models.CASCADE)
    matiere = models.ForeignKey(Matiere, on_delete=models.CASCADE)
    annee = models.CharField(max_length=20)

gestion_scolaire/cours/forms.py
from django import forms
from datetime import date

from parcours.models import Specialite
from enseignants.models import Enseignant

from .models import Module, GRADES, SEMESTRES


year = date.today().year - 3

ANNEES = (
    ((f'{year}{" - "}{year + 1}'), (f'{year}{" - "}{year + 1}')),
    ((f'{year + 1}{" - "}{year + 2}'), (f'{year + 1}{" - "}{year + 2}')),
    ((f'{year + 2}{" - "}{year + 3}'), (f'{year + 2}{" - "}{year + 3}')),
    ((f'{year + 3}{" - "}{year + 4}'), (f'{year + 3}{" - "}{year + 4}')),
    ((f'{year + 4}{" - "}{year + 5}'), (f'{year + 4}{" - "}{year + 5}')),
    ((f'{year + 5}{" - "}{year + 6}'), (f'{year + 5}{" - "}{year + 6}')),
)


class ModuleCreationForm(forms.Form):
    specialite = forms.ModelChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Spécialité",
            }
        ),
        queryset=Specialite.objects.all(),
        empty_label="------------------------------",
    )
    grade = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Grade",
            }
        ),
        choices=GRADES,
    )
    semestre = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Semestre",
            }
        ),
        choices=SEMESTRES,
    )
    code = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Code",
            }
        ),
        max_length=255,
    )
    nom = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Nom",
            }
        ),
        max_length=255,
    )


class MatiereCreationForm(forms.Form):
    module = forms.ModelChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Module",
            }
        ),
        queryset=Module.objects.all(),
        empty_label="------------------------------",
    )
    code = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Code",
            }
        ),
        max_length=255,
    )
    nom = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Nom",
            }
        ),
        max_length=255,
    )
    credit = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control shadow-none",
                "id": "floatingInput",
                "placeholder": "Crédit",
            }
        ),
        max_length=2,
    )


class ProgrammeCreationForm(forms.Form):
    enseignant = forms.ModelChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Enseignant",
            }
        ),
        queryset=Enseignant.objects.all(),
        empty_label="------------------------------",
    )
    annee = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select shadow-none",
                "id": "floatingInput",
                "placeholder": "Année Académique",
            }
        ),
        choices=ANNEES,
    )

gestion_scolaire/cours/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test

from staffs.views import is_staff, is_not_anonymous, is_enseignant
from enseignants.models import Enseignant

from .forms import ModuleCreationForm, MatiereCreationForm, ProgrammeCreationForm
from .models import Module, Matiere, Attribution


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_staff, login_url="/")
@login_required(login_url="/")
def create_module(request):
    if request.method == "POST":
        form = ModuleCreationForm(request.POST)

        if form.is_valid():
            specialite = form.cleaned_data["specialite"]
            grade = form.cleaned_data["grade"]
            semestre = form.cleaned_data["semestre"]
            code = form.cleaned_data["code"]
            nom = form.cleaned_data["nom"]

            Module.objects.create(
                specialite=specialite,
                grade=grade,
                semestre=semestre,
                code=code,
                nom=nom,
            )

            return redirect("cours:modules")

    form = ModuleCreationForm()
    return render(request, "cours/module_creation.html", {"form": form})


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_staff, login_url="/")
@login_required(login_url="/")
def create_matiere(request):
    if request.method == "POST":
        form = MatiereCreationForm(request.POST)

        if form.is_valid():
            module = form.cleaned_data["module"]
            code = form.cleaned_data["code"]
            nom = form.cleaned_data["nom"]
            credit = form.cleaned_data["credit"]

            Matiere.objects.create(module=module, code=code, nom=nom, credit=credit)

            return redirect("cours:matieres")

    form = MatiereCreationForm()
    return render(request, "cours/matiere_creation.html", {"form": form})


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_staff, login_url="/")
@login_required(login_url="/")
def module_list_view(request):
    queryset = Module.objects.all()

    if request.method == "POST":
        form = ModuleCreationForm(request.POST)

        if form.is_valid():
            specialite = form.cleaned_data["specialite"]
            semestre = form.cleaned_data["semestre"]
            grade = form.cleaned_data["grade"]
            code = form.cleaned_data["code"]
            nom = form.cleaned_data["nom"]

            Module.objects.create(
                specialite=specialite,
                semestre=semestre,
                grade=grade,
                code=code,
                nom=nom,
            )

            return redirect("cours:modules")

    form = ModuleCreationForm()
    context = {"modules": queryset, "form": form}
    return render(request, "cours/module_list.html", context)


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_staff, login_url="/")
@login_required(login_url="/")
def matiere_list_view(request):
    queryset = Matiere.objects.all()

    if request.method == "POST":
        form = MatiereCreationForm(request.POST)

        if form.is_valid():
            module = form.cleaned_data["module"]
            code = form.cleaned_data["code"]
            nom = form.cleaned_data["nom"]
            credit = form.cleaned_data["credit"]

            Matiere.objects.create(module=module, code=code, nom=nom, credit=credit)

            return redirect("cours:matieres")

    form = MatiereCreationForm()
    context = {"matieres": queryset, "form": form}
    return render(request, "cours/matiere_list.html", context)


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_enseignant, login_url="/")
@login_required(login_url="/")
def enseignant_matiere_list_view(request):
    enseignant = get_object_or_404(Enseignant, pk=request.user.pk)
    matieres = Attribution.objects.filter(enseignant=enseignant)

    context = {"enseignant": enseignant, "matieres": matieres}
    return render(request, "cours/matiere_list.html", context)


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_enseignant, login_url="/")
@login_required(login_url="/")
def matiere_view(request):
    queryset = Matiere.objects.all()

    # if request.method == "POST":
    #     form = MatiereCreationForm(request.POST)

    #     if form.is_valid():
    #         module = form.cleaned_data["module"]
    #         code = form.cleaned_data["code"]
    #         nom = form.cleaned_data["nom"]
    #         credit = form.cleaned_data["credit"]

    #         Matiere.objects.create(module=module, code=code, nom=nom, credit=credit)

    #         return redirect("cours:matieres")

    # form = MatiereCreationForm()
    context = {"matieres": queryset}
    return render(request, "cours/dashboard.html", context)


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_staff, login_url="/")
@login_required(login_url="/")
def cours_dashboard_view(request):
    modules = Module.objects.all()
    matieres = Matiere.objects.all()
    context = {"modules": modules, "matieres": matieres}
    return render(request, "cours/dashboard.html", context)


@user_passes_test(is_not_anonymous, login_url="/")
@user_passes_test(is_staff, login_url="/")
@login_required(login_url="/")
def matiere_detail_view(request, pk):
    matiere = get_object_or_404(Matiere, pk=pk)

    if request.method == "POST":
        form = ProgrammeCreationForm(request.POST)

        if form.is_valid():
            enseignant = form.cleaned_data["enseignant"]
            annee = form.cleaned_data["annee"]

            if not Attribution.objects.filter(
                enseignant=enseignant, matiere=matiere, annee=annee
            ).exists():
                Attribution.objects.create(
                    enseignant=enseignant, matiere=matiere, annee=annee
                )

            return redirect("cours:matieres")

    form = ProgrammeCreationForm()
    context = {"matiere": matiere, "form": form}
    return render(request, "cours/matiere_detail.html", context)

gestion_scolaire/templates/cours/dashboard.html
{% extends "dashboard.html" %}


{% block body %}
{% url "parcours:ajouter_domain" as add_domain_url %}
<div class="container-fluid p-0 mb-3">
	<div class="row row-cols-2 gx-3">
		<div class="col">
			<div class="bg-white p-3 shadow" style="height: 150px;">
				<div class="h4 mb-3">Modules</div>
				<div class="h1">200</div>
			</div>
		</div>
		<div class="col">
			<div class="bg-white p-3 shadow" style="height: 150px;">
				<div class="h4 mb-3">Matières</div>
				<div class="h1">200</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

gestion_scolaire/templates/cours/matiere_creation.html
{% extends "dashboard.html" %}

{% block body %}
<div class="bg-white shadow-sm p-3">
   <div class="row mb-3">
      <h2>Ajouter un matière</h2>
   </div>
   <form class="row row-cols-2 g-3" method="POST">
      {% csrf_token %}
      <div class="col">
         <div class="form-floating mb-3">
            {{ form.module }}
            <label for="floatingInput">Module</label>
         </div>
         <div class="form-floating mb-3">
            {{ form.code }}
            <label for="floatingInput">Code</label>
         </div>
         <div class="form-floating mb-3">
            {{ form.nom }}
            <label for="floatingInput">Intitulé</label>
         </div>
         <div class="form-floating mb-3">
            {{ form.credit }}
            <label for="floatingInput">Crédit</label>
         </div>
         <button type="submit" class="w-100 btn btn-lg btn-primary">Enregistrer</button>
      </div>
   </form>
</div>
{% endblock %}

gestion_scolaire/templates/cours/matiere_detail.html
{% extends "dashboard.html" %}


{% block body %}
<div class="col-12 bg-white shadow-sm p-3 pb-4 mb-3">
	<div class="row row-cols-2 mb-4">
		<div class="col">
			<h2 id="">Attribuer une matière</h2>
		</div>
	</div>
	<form class="row row-cols-2 g-3" method="POST">
		{% csrf_token %}
		<div class="col">
			<div class="form-floating mb-3">
				{{ form.enseignant }}
				<label for="floatingInput">Enseignant</label>
			</div>
			<div class="row row-cols-2 gx-3">
				<div class="col">
					<div class="form-floating">
						{{ form.annee }}
						<label for="floatingInput">Annéé académique</label>
					</div>
				</div>
				<div class="col mh-100">
					<button type="submit" class="btn btn-lg btn-primary w-100 h-100">Attribuer</button>
				</div>
			</div>	
		</div>
	</form>
</div>
{% endblock %}

gestion_scolaire/templates/cours/matiere_list.html
{% extends "dashboard.html" %}


{% block body %}
{% url "cours:ajouter_matiere" as add_matiere_url %}
{% url "cours:matieres" as list_matiere_url %}

{% if request.user.type_de_compte == 'ST' %}
{% if request.path == add_matiere_url %}
<div class="col-12 bg-white shadow-sm p-3 pb-4 mb-3">
	<div class="row row-cols-2 mb-4">
		<div class="col">
			<h2 id="">Ajouter une matière</h2>
		</div>
		<div class="col-auto ms-auto">
			<a href="{{ list_matiere_url }}" class="link-secondary text-decoration-none">Fermer</a>
		</div>
	</div>
	<form class="row row-cols-2 g-3" method="POST">
		{% csrf_token %}
		<div class="col">
			<div class="form-floating mb-3">
				{{ form.module }}
				<label for="floatingInput">Module</label>
			</div>
			<div class="row row-cols-2 gx-3">
				<div class="col">
					<div class="form-floating mb-3">
						{{ form.code }}
						<label for="floatingInput">Code</label>
					</div>
				</div>
				<div class="col">
					<div class="form-floating mb-3">
						{{ form.credit }}
						<label for="floatingInput">Crédit</label>
					</div>
				</div>
			</div>
			<div class="form-floating mb-3">
				{{ form.nom }}
				<label for="floatingInput">Matière</label>
			</div>
			<button type="submit" class="btn btn-lg btn-primary w-100">Enregistrer</button>
		</div>
	</form>
</div>
{% endif %}

<div class="col-12 bg-white shadow-sm p-3">
	<div class="row row-cols-2 mb-3">
		<div class="col">
			<h2>Liste de matières</h2>
		</div>
		<div class="col-auto ms-auto">
			{% if request.path == list_matiere_url %}
			<a class="btn btn-secondary" href="{{ add_matiere_url }}" role="button">Ajouter</a>
			{% endif %}
		</div>
	</div>
	<div class="row">
		<div class="col-12 table-responsive">
			<table class="table table-striped table-sm">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">Code</th>
						<th scope="col">Matière</th>
						<th scope="col">Crédit</th>
						<th scope="col">Module</th>
						<th scope="col">Semestre</th>
						<th scope="col">Grade</th>
						<th scope="col">Spécialité</th>
						<th scope="col"></th>
					</tr>
				</thead>
				<tbody>
					{% for matiere in matieres %}
					<tr>
						<td>{{ forloop.counter }}</td>
						<td>{{ matiere.code }}</td>
						<td>{{ matiere.nom }}</td>
						<td>{{ matiere.credit }}</td>
						<td>{{ matiere.module.nom }}</td>
						<td>{{ matiere.module.semestre }}</td>
						<td>{{ matiere.module.grade }}</td>
						<td>{{ matiere.module.specialite.sigle }}</td>
						<td>
							<a href="{% url 'cours:matiere' matiere.pk %}" class="text-decoration-none">Attribuer</a>
						</td>
					</tr>
					{% endfor  %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% elif request.user.type_de_compte == 'EN' %}
{% if programmes.count != 0 %}
<div class="col-12 bg-white shadow-sm p-3">
	<div class="row row-cols-2 mb-3">
		<div class="col">
			<h2>Matières en charge</h2>
		</div>
		<div class="col-auto ms-auto">
			{% if request.path == list_enseignant_url %}
			<a class="btn btn-secondary" href="{{ add_enseignant_url }}" role="button">Ajouter</a>
			{% endif %}
		</div>
	</div>
	<div class="row">
		<div class="col-12 table-responsive">
			<table class="table table-striped table-sm">
				<thead>
					<tr>
						<th scope="col">Code</th>
						<th scope="col">Matière</th>
						<th scope="col">Crédit</th>
						<th scope="col">Semestre</th>
						<th scope="col">Grade</th>
						<th scope="col">Année</th>
						<th scope="col"></th>
					</tr>
				</thead>
				<tbody>
					{% for programme in programmes %}

					<tr>
						<td>{{ programme.matiere.code }}</td>
						<td>{{ programme.matiere.nom }}</td>
						<td>{{ programme.matiere.credit }}</td>
						<td>{{ programme.matiere.module.semestre }}</td>
						<td>{{ programme.matiere.module.grade }}</td>
						<td>{{ programme.annee }}</td>
						<td>
							<a href="{% url 'notes:ajouter' programme.pk %}" class="text-decoration-none">Evaluation</a>
						</td>
					</tr>
					{% endfor  %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% else %}
<div class="col-12 bg-white shadow-sm p-3">
	<div class="row">
		<div class="col">
			<h2 class="text-secondary">Aucune matière ne vous ai encore attribuée </h2>
		</div>
	</div>
</div>
{% endif %}
{% else %}
{% endif %}
{% endblock %}

gestion_scolaire/templates/cours/module_creation.html
{% extends "dashboard.html" %}

{% block body %}
<div class="bg-white shadow-sm p-3">
   <div class="row mb-3">
      <h2>Ajouter un matière</h2>
   </div>
   <form class="row row-cols-2 g-3" method="POST">
      {% csrf_token %}
      <div class="col">
         <div class="form-floating mb-3">
            {{ form.specialite }}
            <label for="floatingInput">Spécialité</label>
         </div>
          <div class="form-floating mb-3">
            {{ form.semestre }}
            <label for="floatingInput">Semestre</label>
         </div>
         <div class="form-floating mb-3">
            {{ form.code }}
            <label for="floatingInput">Code</label>
         </div>
         <div class="form-floating mb-3">
            {{ form.nom }}
            <label for="floatingInput">Intitulé</label>
         </div>
         <button type="submit" class="w-100 btn btn-lg btn-primary">Enregistrer</button>
      </div>
   </form>
</div>
{% endblock %}

gestion_scolaire/templates/cours/module_list.html
{% extends "dashboard.html" %}


{% block body %}
{% url "cours:ajouter_module" as add_module_url %}
{% url "cours:modules" as list_module_url %}

{% if request.path == add_module_url %}
<div class="col-12 bg-white shadow-sm p-3 pb-4 mb-3">
	<div class="row row-cols-2 mb-4">
		<div class="col">
			<h2 id="">Ajouter un module</h2>
		</div>
		<div class="col-auto ms-auto">
			<a href="{{ list_module_url }}" class="link-secondary text-decoration-none">Fermer</a>
		</div>
	</div>
	<form class="row row-cols-2 g-3" method="POST">
		{% csrf_token %}
		<div class="col">
			<div class="form-floating mb-3">
				{{ form.specialite }}
				<label for="floatingInput">Spécialité</label>
			</div>
			<div class="row row-cols-2 gx-3">
				<div class="col">
					<div class="form-floating mb-3">
						{{ form.grade }}
						<label for="floatingInput">Grade</label>
					</div>
				</div>
				<div class="col">
					<div class="form-floating mb-3">
						{{ form.semestre }}
						<label for="floatingInput">Semestre</label>
					</div>
				</div>
			</div>
			<div class="form-floating mb-3">
				{{ form.nom }}
				<label for="floatingInput">Module</label>
			</div>
			<div class="row row-cols-2 gx-3">
				<div class="col">
					<div class="form-floating">
						{{ form.code }}
						<label for="floatingInput">Code</label>
					</div>
				</div>
				<div class="col">
					<button type="submit" class="btn btn-lg btn-primary w-100 h-100">Enregistrer</button>	
				</div>
			</div>			
		</div>
	</form>
</div>
{% endif %}

<div class="col-12 bg-white shadow-sm p-3">
	<div class="row row-cols-2 mb-3">
		<div class="col">
			<h2>Liste de modules</h2>
		</div>
		<div class="col-auto ms-auto">
			{% if request.path == list_module_url %}
			<a class="btn btn-secondary" href="{{ add_module_url }}" role="button">Ajouter</a>
			{% endif %}
		</div>
	</div>
	<div class="row">
		<div class="col-12 table-responsive">
			<table class="table table-striped table-sm">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">Code</th>
						<th scope="col">Module</th>
						<th scope="col">Semestre</th>
						<th scope="col">Grade</th>
						<th scope="col">Spécialité</th>
					</tr>
				</thead>
				<tbody>
					{% for module in modules %}
					<tr>
						<td>{{ forloop.counter }}</td>
						<td>{{ module.code }}</td>
						<td>{{ module.nom }}</td>
						<td>{{ module.semestre }}</td>
						<td>{{ module.grade }}</td>
						<td>{{ module.specialite.nom }}</td>
					</tr>
					{% endfor  %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}